name: WhatsApp Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            python3 \
            python3-pip \
            python-is-python3

      - name: Install Chrome
        run: |
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
    
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: npm install

      - name: Run Bot 
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GITTOKEN: ${{ secrets.GITTOKEN }} 
        run: npm start
